sudo: required

language: Go
arch:
    - arm64
    - amd64
services:
  - docker

script:
  - PWD= pwd
  - echo $PWD
  - docker pull alpine:latest
  - bash ./buildscript/docker_run.sh build_alpine.sh

